version: '3.8'

services:
  mongodb:
    image: mongo:4.9
    container_name: mongodb_face
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin123
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27020:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - face_network

  face_logger:
    build: .
    container_name: face_logger
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./PPM-Project:/projectface/PPM-Project   # log file folder
      - ./face_log_to_mongo.py:/app/face_log_to_mongo.py
    working_dir: /app
    command: ["python3", "face_log_to_mongo.py"]
    networks:
      - face_network

networks:
  face_network:
    driver: bridge
